// with-qwik/src/routes/thank-you/index.tsx
import { component$ } from '@builder.io/qwik'
import type { DocumentHead } from '@builder.io/qwik-city'

export default component$(() => {
  return (
    <>
      <h1>Thank you page</h1>
    </>
  )
})

export const head: DocumentHead = {
  title: 'Welcome to Qwik',
  meta: [
    {
      name: 'description',
      content: 'Qwik site description',
    },
  ],
  scripts: [
    {
      script: `
        (function(t,d,k){(t[k]=t[k]||[]).push(d);t[d]=t[d]||t[k].f||function(){(t[d].q=t[d].q||[]).push(arguments)}})(window,"trackdesk","TrackdeskObject");
          trackdesk("policka", "conversion", {
    "conversionType": "sale"
  });`,
    },
  ],
}

// with-nuxt/pages/thank-you.vue
<script setup lang="ts">
    useHead({
        script: [
            { innerHTML: `
                (function(t,d,k){(t[k]=t[k]||[]).push(d);t[d]=t[d]||t[k].f||function(){(t[d].q=t[d].q||[]).push(arguments)}})(window,"trackdesk","TrackdeskObject");
                trackdesk("robocop", "conversion", {
                    "conversionType": "sale"
                }); `
            }
        ]
    })
</script>

<template>
    <h1>Thank you page</h1>
</template>
